Install-WindowsFeature Net-Framework-Core -source d:\sources\sxs
Install-WindowsFeature BITS -source d:\sources\sxs
Install-WindowsFeature GPMC -source d:\sources\sxs
Install-WindowsFeature RDC -source d:\sources\sxs
Install-WindowsFeature RSAT -source d:\sources\sxs
Install-WindowsFeature Web-Windows-Auth -source d:\sources\sxs
Install-WindowsFeature Web-ISAPI-Ext -source d:\sources\sxs
Install-WindowsFeature Web-Metabase -source d:\sources\sxs
Install-WindowsFeature Web-WMI -source d:\sources\sxs
Install-WindowsFeature NET-Framework-Features -source d:\sources\sxs
Install-WindowsFeature Web-Asp-Net -source d:\sources\sxs
Install-WindowsFeature Web-Asp-Net45 -source d:\sources\sxs
Install-WindowsFeature NET-HTTP-Activation -source d:\sources\sxs
Install-WindowsFeature NET-Non-HTTP-Activ -source d:\sources\sxs